bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booksapp/', include('booksapp.urls')),
    path('', RedirectView.as_view(url='booksapp')),
    path('accounts/', include('django.contrib.auth.urls')),

]

handler403 = 'booksapp.views.custom403'
handler404 = 'booksapp.views.custom404'

booksapp/urls.py
from django.urls import path
from .import views

app_name = 'booksapp'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),  # Home View
    path('country_list', views.CountryListView.as_view(), name='country_list'),  # country list view
    path('country_create', views.CountryCreateView.as_view(), name='country_create'),  # country create view
    path('country_update/<int:pk>', views.CountryUpdateView.as_view(), name='country_update'),  # country update view
    path('country_delete/<int:pk>', views.CountryDeleteView.as_view(), name='country_delete'),  # country delete view

    path('language_list', views.LanguageListView.as_view(), name='language_list'),  # language list view
    path('language_create', views.LanguageCreateView.as_view(), name='language_create'),  # language create view
    path('language_update/<int:pk>', views.LanguageUpdateView.as_view(), name='language_update'),  # language create view
    path('language_delete/<int:pk>', views.LanguageDeleteView.as_view(), name='language_delete'),  # language delete view

    path('author_list', views.AuthorListView.as_view(), name='author_list'),  # author list view
    path('author_create', views.AuthorCreateView.as_view(), name='author_create'),  # author create view
    path('author_update/<int:pk>', views.AuthorUpdateView.as_view(), name='author_update'),  # author update view
    path('author_detail/<int:pk>', views.AuthorDetailView.as_view(), name='author_detail'),  # author detail view
    path('author_delete/<int:pk>', views.AuthorDeleteView.as_view(), name='author_delete'),  # author delete view

    path('book_list', views.BookListView.as_view(), name='book_list'),  # book list view
    path('book_create', views.BookCreateView.as_view(), name='book_create'),  # book create view
    path('book_update/<int:pk>', views.BookUpdateView.as_view(), name='book_update'),  # book update view
    path('book_detail/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),  # book detail view
    path('book_delete/<int:pk>', views.BookDeleteView.as_view(), name='book_delete'),  # book delete view
]

booksapp/models.py
import datetime

from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import (MinLengthValidator, MinValueValidator, MaxValueValidator)


# Create your models here.
class Country(models.Model):
    # country name with max length 50, min length 3 letter
    country = models.CharField(max_length=50, validators=[MinLengthValidator(3)])

    class Meta:
        verbose_name_plural = 'countries'

    # et ei naitaks obj1, obj2 jne vaid naitaks riiginime
    def __str__(self):
        return self.country

class Language(models.Model):
    language = models. CharField(max_length=50, validators=[MinLengthValidator(3)])

    def __str__(self):
        return self.language

class Author(models.Model):
    firstname = models.CharField(max_length=25, validators=[MinLengthValidator(2)])
    lastname = models.CharField(max_length=25, validators=[MinLengthValidator(2)])
    birth = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)

    class Meta:
        # default order lastname and then firstname
        ordering = ['lastname', 'firstname']

    def fullname(self):
        """ show fullname of author """
        return f'{self.firstname} {self.lastname}'


    def __str__(self):
        """
        default ADMIN page view
        """
        return f'{self.fullname()}, {self.birth}, {self.country}'

def validate_digits_length(isbn):
    """ check ISBN number digits and length """
    if not (isbn.isdigit() and len(isbn) == 13):
        return ValidationError('The ISBN number must be 13 digits long and no letters')

def max_value_current_year(year):
    """" return current year (year)"""
    return MaxValueValidator(datetime.date.today().year)(year)

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    book_language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)
    isbn = models.CharField(verbose_name='ISBN number', max_length=13, validators=[validate_digits_length])
    number_of_pages = models.PositiveIntegerField(validators=[MinValueValidator(2)])
    description = models.TextField(null=True, blank=True)  # st et taitmine ei ole kohustuslik
    book_published_year = models.PositiveIntegerField(validators=[MinValueValidator(1900), max_value_current_year])  # lubatud on aastad 1900 kaasa arvatud kuni tänane paev


    class Meta:
        """
        default result ordering - sotreerimine
        """
        ordering = ['title']

    def book_info(self):
        """
        show simple book info
        """
        return f'{self.title}, {self.author.fullname()}'

    def __str__(self):
       """
       admin page show info
       """
       return f'{self.title}, {self.author}, {self.book_language}, {self.isbn}, {self.number_of_pages}, {self.book_published_year}, {self.description[:25]}'

booksapp/forms.py
from django import forms
import bookproject.settings
from .models import *


class LanguageCreateForm(forms.ModelForm):
    language = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter a new language name', 'class': 'form-control', 'autofocus': True,}))

    class Meta:
        model = Language
        fields = ['language']  # voib ka kirj '__all__'


class AuthorCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control mb-2'
            # comment
            # visible.field.widget.attrs['placeholder'] = visible.field.label

        self.fields['firstname'].widget.attrs['autofocus'] = True
        self.fields['birth'].widget = forms.widgets.DateInput(attrs={'type': 'date', 'class': 'form/control mb-2'})


    class Meta:
        model = Author
        fields = '__all__'


class BookCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control mb-2'
            # comment
            # visible.field.widget.attrs['placeholder'] = visible.field.label

        self.fields['title'].widget.attrs['autofocus'] = True
        self.fields['book_published_year'].widget = forms.widgets.TextInput(attrs={'type': 'number',
                                                                                   'class': 'form-control mb-2',
                                                                                   'min':1900, 'step': 1,})

    class Meta:
        model = Book
        fields = '__all__'


# class LanguageUpdateForm(forms.ModelForm):

booksapp/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView)

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .forms import *  # all created forms
from .models import *  # all created models

#tegime hiljem selle
class WriterRequiredMixin(UserPassesTestMixin):
    """ Test: user in group Writer"""
    def test_func(self):
        return self.request.user.groups.filter(name='Writer').exists()
class EditorRequiredMixin(UserPassesTestMixin):
    # delete view
    def test_func(self):
        return self.request.user.groups.filter(name='Editor').exists()

# Create your views here.
class HomeView(TemplateView):
    template_name = 'booksapp/index.html'


class CountryListView(ListView):
    # template_name = 'booksapp/country_list.html'
    model = Country
    # order result by country field name
    queryset = Country.objects.order_by('country')
    context_object_name = 'countries'  # object_list is default


class LanguageListView(ListView):
    # template languge_list.html
    #context_object_name is object_list
    model = Language
    queryset = Language.objects.order_by('language')


class AuthorListView(ListView):
    model = Author


class BookListView(ListView):
    model = Book


class CountryCreateView(WriterRequiredMixin, CreateView):
    model = Country
    fields = '__all__'  # all fields from model
    success_url = reverse_lazy('booksapp:country_list')


class LanguageCreateView(WriterRequiredMixin, CreateView):
    model = Language
    form_class = LanguageCreateForm
    success_url = reverse_lazy('booksapp:language_list')


class AuthorCreateView(WriterRequiredMixin, CreateView):
    model = Author
    form_class = AuthorCreateForm
    success_url = reverse_lazy('booksapp:author_list')


class BookCreateView(WriterRequiredMixin, CreateView):
    model = Book
    form_class = BookCreateForm
    success_url = reverse_lazy('booksapp:book_list')


class CountryUpdateView(WriterRequiredMixin, UpdateView):
    template_name = 'booksapp/country_form_update.html'
    model = Country
    fields = '__all__'
    success_url = reverse_lazy('booksapp:country_list')

    def form_valid(self,form):
        # additional checks
        return super().form_valid(form)

class LanguageUpdateView(WriterRequiredMixin, UpdateView):
    template_name = 'booksapp/language_form_update.html'
    model = Language
    form_class = LanguageCreateForm
    success_url = reverse_lazy('booksapp:language_list')

    def form_valid(self,form):
        # additional checks
        return super().form_valid(form)

class AuthorUpdateView(WriterRequiredMixin, UpdateView):
    template_name = 'booksapp/author_form_update.html'
    model = Author
    form_class = AuthorCreateForm
    success_url = reverse_lazy('booksapp:author_list')

    def form_valid(self, form):
        # additional checks
        return super().form_valid(form)

class BookUpdateView(WriterRequiredMixin, UpdateView):
    template_name = 'booksapp/book_form_update.html'
    model = Book
    form_class = BookCreateForm
    success_url = reverse_lazy('booksapp:book_list')

    def form_valid(self, form):
        # additional checks
        return super().form_valid(form)


class AuthorDetailView(DetailView):
    # default template:
    # model_detail.html => author_detail.html
    model = Author


class BookDetailView(DetailView):
    # template_name = 'booksapp/book_detail.html'
    model = Book


class CountryDeleteView(EditorRequiredMixin, DeleteView):
    # model-confirm_delete.html => country_confirm_delete
    model = Country
    success_url = reverse_lazy('booksapp:country_list')

class LanguageDeleteView(EditorRequiredMixin, DeleteView):
    # template_name = 'booksapp/language_delete'
    model = Language
    success_url = reverse_lazy('booksapp:language_list')


class AuthorDeleteView(EditorRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('booksapp:author_list')


class BookDeleteView(EditorRequiredMixin, DeleteView):

    model = Book
    success_url = reverse_lazy('booksapp:book_list')


def custom403(request, exception):
    return render(request, '403.html', status=403)

def custom404(request, exception):
    return render(request, '404.html', status=404)

booksapp/templates/booksapp/author_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
	<div class="row mt-2">
    <div class="col-6 mx-auto">
        <div class="card mb-3">
            <div class="card-header text-bg-danger">
                Delete author
            </div>
            <div class="card-body">
                <div class="alert alert-info" role="alert">
                    Wherever this author {{ author }} is used, it will be replaced by NULL
                </div>
                <p>Are you sure you want to delete the author {{ author }}?</p>
                <form method="post">
                {% csrf_token %}
                <input type="submit" value="Confirm delete" class="btn btn-danger col-4">
                 </form>
            </div>

            </div>
        </div>
        <a href="{% url 'booksapp:author_list' %}">List of authors</a>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/author_detail.html
{% extends 'base.html' %}
{% block content %}
	<div class="row">
    <div class="col-8 mt-2 mx-auto">
        <h3>Detailed information about the author {{ author.fullname }}</h3>
        <table class="table table-bordered">
            <tr>
                <td>Fullname</td>
                <td>{{ author.fullname }}</td>
            </tr>
              <tr>
                <td>First name</td>
                <td>{{ author.firstname }}</td>
            </tr>
            <tr>
                <td>Last name</td>
                <td>{{ author.lastname }}</td>
            </tr>
            <tr>
                <td>Birth</td>
                <td>{{ author.birth|date:'d.m.Y'}}</td>
            </tr>
            <tr>
                <td>Country</td>
                <td>{{ author.country }}</td>
            </tr>
        </table>
        <p class="text-end">
            <a href="{% url 'booksapp:author_list' %}">List on authors</a>
        </p>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/author_form.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
    <div class="col-5 mx-auto">
        <h3>Add a new author</h3>
        <form method="post" class="form">
            {% csrf_token %}

            {% for field in form %}
            	<div class="form-field">
                    <label for="{{ field.id_for_label }}" class="fw-bold">{{ field.label }}</label>
                    {#  show errors IF #}
                    {% for error in field.errors %}
                    	{% if field.errors %}
                    		<div class="alert alert-danger mt-1">
                            {{ error }}
                            </div>
                    	{% endif %}
                    {% endfor %}

                    {{ field }}
                </div>
            {% endfor %}

            <input type="submit" value="Add a new author" class="btn btn-primary mt-2">
        </form>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/author_form_update.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
    <div class="col-5 mx-auto">
        <h3>Update author <span class="fw-bold">{{ author.fullname }}</span></h3>
        <form method="post" class="form">
            {% csrf_token %}

            {% for field in form %}
            	<div class="form-field">
                    <label for="{{ field.id_for_label }}" class="fw-bold">{{ field.label }}</label>
                    {#  show errors IF #}
                    {% for error in field.errors %}
                    	{% if field.errors %}
                    		<div class="alert alert-danger mt-1">
                            {{ error }}
                            </div>
                    	{% endif %}
                    {% endfor %}

                    {{ field }}
                </div>
            {% endfor %}

            <input type="submit" value="Update" class="btn btn-success mt-2">
        </form>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/author_list.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
    <div class="row">
        <div class="col-8 mx-auto">
            <h3>Show authors</h3>
            <table class="table table-bordered table-hover">
                <thead>
                <tr class="text-center">
                    <th>Author</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for author in object_list %} {# default is object_list (author) must be views.py #}
                	<tr>
                    <td>{{ author.fullname }}</td>
                    <td class="text/center">
                        {% if user.is_authenticated %}
                        <a href="{% url 'booksapp:author_update' pk=author.id %}">Update</a>
                        <a href="{% url 'booksapp:author_delete' pk=author.id %}" class="text-danger">Delete</a>
                        {% endif %}
                        <a href="{% url 'booksapp:author_detail' pk=author.id%}" class="text-warning">Detail</a>
                    </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            <a href="{% url 'booksapp:author_create' %}">Add a new author</a>
        </div>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/book_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
	<div class="row mt-2">
    <div class="col-6 mx-auto">
        <div class="card mb-3">
            <div class="card-header text-bg-danger">
                Delete book
            </div>
            <div class="card-body">
                <div class="alert alert-info" role="alert">
                    Wherever this book {{ book.title }} is used, it will be replaced by NULL
                </div>
                <p>Are you sure you want to delete the book {{ book.title }}?</p>
                <form method="post">
                {% csrf_token %}
                <input type="submit" value="Confirm delete" class="btn btn-danger col-4">
                 </form>
            </div>

            </div>
        </div>
        <a href="{% url 'booksapp:book_list' %}">List of books</a>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/book_detail.html
{% extends 'base.html' %}
{% block content %}
	<div class="row">
    <div class="col-8 mt-2 mx-auto">
        <h3>Detailed information about the book {{ book.title }}</h3>
        <table class="table table-bordered">
            <tr>
                <td>Title</td>
                <td>{{ book.title }}</td>
            </tr>
              <tr>
                <td>Author</td>
                <td>{{ book.author }}</td>
            </tr>
            <tr>
                <td>Book language</td>
                <td>{{ book.book_language }}</td>
            </tr>
            <tr>
                <td>ISBN</td>
                <td>{{ book.isbn }}</td>
            </tr>
            <tr>
                <td>Number of pages</td>
                <td>{{ book.number_of_pages }}</td>
            </tr>
            <tr>
                <td>Description</td>
                <td>{{ book.description }}</td>
            </tr>
            <tr>
                <td>Book published year</td>
                <td>{{ book.book_published_year }}</td>
            </tr>
        </table>
        <p class="text-end">
            <a href="{% url 'booksapp:book_list' %}">List on books</a>
        </p>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/book_form.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
    <div class="col-5 mx-auto">
        <h3>Add a new book</h3>
        <form method="post" class="form">
            {% csrf_token %}

            {% for field in form %}
            	<div class="form-field">
                    <label for="{{ field.id_for_label }}" class="fw-bold">{{ field.label }}</label>
                    {#  show errors IF #}
                    {% for error in field.errors %}
                    	{% if field.errors %}
                    		<div class="alert alert-danger mt-1">
                            {{ error }}
                            </div>
                    	{% endif %}
                    {% endfor %}

                    {{ field }}
                </div>
            {% endfor %}

            <input type="submit" value="Add a new book" class="btn btn-primary mt-2">
        </form>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/book_form_update.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
    <div class="col-5 mx-auto">
        <h3>Update book <span class="fw-bold">{{ book.title }}</span></h3>
        <form method="post" class="form">
            {% csrf_token %}

            {% for field in form %}
            	<div class="form-field">
                    <label for="{{ field.id_for_label }}" class="fw-bold">{{ field.label }}</label>
                    {#  show errors IF #}
                    {% for error in field.errors %}
                    	{% if field.errors %}
                    		<div class="alert alert-danger mt-1">
                            {{ error }}
                            </div>
                    	{% endif %}
                    {% endfor %}

                    {{ field }}
                </div>
            {% endfor %}

            <input type="submit" value="Update" class="btn btn-success mt-2">
        </form>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/book_list.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
    <div class="row">
        <div class="col-8 mx-auto">
            <h3>Show books</h3>
            <table class="table table-bordered table-hover">
                <thead>
                <tr class="text-center">
                    <th>Book</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for book in object_list %} {# default is object_list (book) must be views.py #}
                	<tr>
                    <td>{{ book.title }}</td>
                    <td class="text/center">
                        {% if user.is_authenticated %}
                        <a href="{% url 'booksapp:book_update' pk=book.id %}">Update</a>
                        <a href="{% url 'booksapp:book_delete' pk=book.id%}" class="text-danger">Delete</a>
                        {% endif %}
                        <a href="{% url 'booksapp:book_detail' pk=book.id %}" class="text-warning">Detail</a>
                    </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            <a href="{% url 'booksapp:book_create' %}">Add a new book</a>
        </div>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/country_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
	<div class="row mt-2">
    <div class="col-6 mx-auto">
        <div class="card mb-3">
            <div class="card-header text-bg-danger">
                Delete country
            </div>
            <div class="card-body">
                <div class="alert alert-info" role="alert">
                    Wherever this country {{ country }} is used, it will be replaced by NULL
                </div>
                <p>Are you sure you want to delete the country {{ country }}?</p>
                <form method="post">
                {% csrf_token %}
                <input type="submit" value="Confirm delete" class="btn btn-danger col-4">
                 </form>
            </div>

            </div>
        </div>
        <a href="{% url 'booksapp:country_list' %}">List of countries</a>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/country_form.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
    <div class="row">
        <div class="col-6 mt-2 mx-auto">
            <h3>Add a new country</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Add a new Country" class="btn btn-primary">
            </form>
        </div>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/country_list.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
    <div class="row">
        <div class="col-8 mx-auto">
            <h3>Show countries</h3>
            <table class="table table-bordered table-hover">
                <thead>
                <tr class="text-center">
                    <th>Country</th>
                    {% if user.is_authenticated %}
                    <th>Action</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for country in countries %} {# default is object_list (countries) #}

                	<tr>

                    <td>{{ country }}</td>
                        {% if user.is_authenticated %}
                    <td class="text/center">
                        <a href="{% url 'booksapp:country_update' pk=country.id %}">Update</a>
                        <a href="{% url 'booksapp:country_delete' pk=country.id %}" class="text-danger">Delete</a>
                        {% endif %}
                    </td>

                    </tr>

                {% endfor %}

                </tbody>
            </table>
            <a href="{% url 'booksapp:country_create' %}">Add a new country</a>
        </div>
    </div>
    </div>
{% endblock %}

booksapp/templates/booksapp/language_form_update.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
    <div class="col-5 mx-auto">
        <h3>Update language <span class="fw-bold">{{ language }}</span></h3>
        <form method="post" class="form">
            {% csrf_token %}

            {% for field in form %}
            	<div class="form-field">
                    <label for="{{ field.id_for_label }}" class="fw-bold">{{ field.label }}</label>
                    {#  show errors IF #}
                    {% for error in field.errors %}
                    	{% if field.errors %}
                    		<div class="alert alert-danger mt-1">
                            {{ error }}
                            </div>
                    	{% endif %}
                    {% endfor %}

                    {{ field }}
                </div>
            {% endfor %}

            <input type="submit" value="Update" class="btn btn-success mt-2">
        </form>
    </div>
    </div>
{% endblock %}