bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booksapp/', include('booksapp.urls')),
    path('', RedirectView.as_view(url='booksapp')),
    path('accounts/', include('django.contrib.auth.urls')),

]

handler403 = 'booksapp.views.custom403'
handler404 = 'booksapp.views.custom404'

booksapp/urls.py
from django.urls import path
from .import views

app_name = 'booksapp'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),  # Home View
    path('country_list', views.CountryListView.as_view(), name='country_list'),  # country list view
    path('country_create', views.CountryCreateView.as_view(), name='country_create'),  # country create view
    path('country_update/<int:pk>', views.CountryUpdateView.as_view(), name='country_update'),  # country update view
    path('country_delete/<int:pk>', views.CountryDeleteView.as_view(), name='country_delete'),  # country delete view

    path('language_list', views.LanguageListView.as_view(), name='language_list'),  # language list view
    path('language_create', views.LanguageCreateView.as_view(), name='language_create'),  # language create view
    path('language_update/<int:pk>', views.LanguageUpdateView.as_view(), name='language_update'),  # language create view
    path('language_delete/<int:pk>', views.LanguageDeleteView.as_view(), name='language_delete'),  # language delete view

    path('author_list', views.AuthorListView.as_view(), name='author_list'),  # author list view
    path('author_create', views.AuthorCreateView.as_view(), name='author_create'),  # author create view
    path('author_update/<int:pk>', views.AuthorUpdateView.as_view(), name='author_update'),  # author update view
    path('author_detail/<int:pk>', views.AuthorDetailView.as_view(), name='author_detail'),  # author detail view
    path('author_delete/<int:pk>', views.AuthorDeleteView.as_view(), name='author_delete'),  # author delete view

    path('book_list', views.BookListView.as_view(), name='book_list'),  # book list view
    path('book_create', views.BookCreateView.as_view(), name='book_create'),  # book create view
    path('book_update/<int:pk>', views.BookUpdateView.as_view(), name='book_update'),  # book update view
    path('book_detail/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),  # book detail view
    path('book_delete/<int:pk>', views.BookDeleteView.as_view(), name='book_delete'),  # book delete view
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Project Book</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        {% include 'menu.html' %}
    </div>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'booksapp:index' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
      {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Adding
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'booksapp:country_create' %}">Country</a></li>
            <li><a class="dropdown-item" href="{% url 'booksapp:language_create' %}">Language</a></li>
            <li><a class="dropdown-item" href="{% url 'booksapp:author_create' %}">Author</a></li>
              <li><a class="dropdown-item" href="{% url 'booksapp:book_create' %}">Book</a></li>
          </ul>
        </li>
      {% endif %}
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Lists
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'booksapp:country_list' %}">List of Countries</a></li>
            <li><a class="dropdown-item" href="{% url 'booksapp:language_list' %}">List of Languages</a></li>
            <li><a class="dropdown-item" href="{% url 'booksapp:author_list' %}">List of Authories</a></li>
              <li><a class="dropdown-item" href="{% url 'booksapp:book_list' %}">List of Books</a></li>
          </ul>
        </li>
              {% if user.is_authenticated %}
    	<span class="nav-link">Welcome {{ user.username }}! <a href="{% url 'logout' %}">Logout</a></span>
    {% else %}
        <span class="nav-link">Welcome guest! <a href="{% url 'login' %}">Login</a></span>
    {% endif %}
      </ul>
    </div>
  </div>
</nav>